Add tests
p-org/P pull request #293
Opened 2020-11-30 06:57 UTC by yzhang90

2020-12-02 23:28 UTC, ankushdesai requested changes
Can you please rebase this pull request with the new master and make sure that the regressions passes?

2020-12-03 00:40 UTC, yzhang90 commented on .github/workflows/dotnetcore.yml
> +        mvn install
yes. we add a new test runner and when you run `dotnet test --configuration Release`, it should run all the tests including the rvm test. If you want to rvm test specifically, you can run with `dotnet test --filter FullyQualifiedName~UnitTests.RvmRuntimeRegression`

2020-12-03 05:36 UTC, ankushdesai requested changes
Everything looks great! 

One minor comment:
Can you create a new step in each github action that runs the rununittests.py as a commend directly instead of through the .net code. 

You can call it Test-RVM step.

2020-12-03 23:04 UTC, virgil-serbanuta commented
> One minor comment:
> Can you create a new step in each github action that runs the rununittests.py as a commend directly instead of through the .net code.
> 
> You can call it Test-RVM step.

I think that's done, does it look reasonable now?

2020-12-04 02:23 UTC, ankushdesai approved these changes
Thanks @yzhang90 and @virgil-serbanuta, this looks great now!

2020-12-04 02:23 UTC, merged