[Portfolio] Add first version of portfolio model checker
p-org/P pull request #554
Opened 2023-01-30 22:31 UTC by aman-goel

Hi @ankushdesai and @soumyasmruti,

This PR adds the first stable version of P's portfolio model checker. Updates include:
- Adds folder named `Portfolio/` that contains P checker's portfolio runner (local) script with a readme
- Adds an example portfolio configuration file `portfolio-config.json` to ClientServer example in the tutorial
- Portfolio checker supports both Coyote and PSym exploration techniques
- TODO: Improved documentation, continuous integration, tests, and other updates to follow in next version

Would be great if you can review and let me know of any suggested changes.

--
Aman

2023-01-30 23:07 UTC, ankushdesai requested changes

2023-01-31 20:01 UTC, ankushdesai requested changes

2023-01-31 20:01 UTC, ankushdesai commented on Portfolio/README.md
> +# P Model Checker Portfolio Runner
@aman-goel

2023-01-31 23:45 UTC, aman-goel commented on Portfolio/README.md
> +# P Model Checker Portfolio Runner
Done, via https://github.com/p-org/P/pull/554/commits/1db6d1414ca5d18f6457375a408499a8ff1fe2e8

2023-02-01 06:14 UTC, ankushdesai approved these changes

2023-02-01 06:14 UTC, merged