[PExplicit] Support stateless DFS with all P lang features
p-org/P pull request #718
Opened 2024-04-12 18:05 UTC by aman-goel

This PR adds several changes to fully implement vanilla stateless depth-first style search with all P language constructs supported. Added GitHub CI action for PExplicit to run regression tests.

Updates include:
- Support loops and related statements (break, continue)
- Support receive statement completely, including:
  - receive inside a loop
  - receive inside a receive
  - receive during state transitions, exit functions, and goto functions
- Revamps PValues to support dynamic type casting from any, collection<any>
- Support PEnum (including custom integer values)
- Support operations on PValues
   - Arithmetic, logical, toInt, toFLoat, etc. in primitive types
   - Add/get/put/set/remove in collection types
   - Get/set in tuple types
- Support raise statement
- Support return statement (including inside loops, receive case block)
- Correct observing events by monitors
- Updates logging
- Fully support dynamic type casting (including over collections and nested collections)
- Corrects choosing random value from a collection
- Update to Java 17
- Catch NullPointerDereference, ClassCast, InvalidCast as bug.
- Simplified PExplicit IR code generator.
- Remove generation of redundant code in IR (e.g., statements after control flow has already returned in a function).
- Adds regression testing and GitHub CI action for PExplicit:
  - Unsupported construct include: null events
  - Track list of non-supported constructs in regression runner [here](https://github.com/p-org/P/blob/d8fbfe34670f79ac714c4c6a50e37faefa928b32/Src/PRuntimes/PExplicitRuntime/src/test/java/pexplicit/TestPExplicit.java#L54-L88)
  - TODO: deadlock and liveness checking

Updates beyond PExplicit codebase include:
- Disable running GitHub CI for PSym/PCover on dev/pexplicit_checker branch for now
- Minor change to .gitignore

2024-04-15 15:32 UTC, ankushdesai requested changes

2024-04-15 17:43 UTC, aman-goel commented on Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/RuntimeExecutor.java
> +        if (!PExplicitGlobal.getStatus().equals("cex")) {
Yes, will do.

2024-04-15 17:49 UTC, aman-goel commented on Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/machine/events/PContinuation.java
> +        // process any pending exit state
Like in this example, [receiveInExit1.p](https://github.com/p-org/P/blob/5e7f6c68e976dc6064fb5dcb52778d715bda5c27/Tst/RegressionTests/Feature2Stmts/Correct/receive14/receiveInExit1.p), a machine can be blocked before it executes the state exit function and as well as after executing the exit function (and before executing the entry function of the new state).

2024-04-15 19:43 UTC, aman-goel commented on Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/RuntimeExecutor.java
> +        if (!PExplicitGlobal.getStatus().equals("cex")) {
Done via [61ef7c3](https://github.com/p-org/P/pull/718/commits/61ef7c3e8b7da6d8e1491472dae6ddcd4a3d8989)

2024-04-15 21:17 UTC, ankushdesai commented on Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/machine/events/PContinuation.java
> +        // process any pending exit state
Yes, but its not logged on the exit and entry at the same time. You code checks both of them and shouldnt there be a check and skip the other check that if its in exit it cannot be in entry?

2024-04-15 23:56 UTC, aman-goel commented on Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/machine/events/PContinuation.java
> +        // process any pending exit state
I cleaned this part up and added detailed comments and assertions to make sure the control flows as expected.
Check changes: https://github.com/p-org/P/compare/61ef7c3...f65d0cd

2024-04-16 20:36 UTC, ankushdesai approved these changes

2024-04-16 23:29 UTC, merged